### ISSUE TITLE
Support for RTU over serial

### ISSUE THREAD

**Issue by schotime** [wolf8196/NModbusAsync#2]
Thanks for the great library.
Because RTU over TCP is now supported, how hard with RTU over serial be to implement?

**Comment by wolf8196** [comment]
Hi. As of now I am not planning any support for serial communication.
First of all, I don't know anything about it :)
Second, I was making this lib in my spare time, but it was solely because of my work project.
And currently there is no plans to support serial. From my understanding it's easier to use some serial to tcp converter.

**Comment by schotime** [comment]
No problem, I'm using FluentModbus now, because it already does. 
Thx for your library.
